[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grounded-eval"
version = "0.1.0"
authors = [
  { name="Josh Longenecker", email="jl@groundedai.com" },
]
description = "A Python package for evaluating LLM application outputs."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "peft>=0.1.0",
    "transformers>=4.0.0",
    "torch>=1.7.0",
    "accelerate>=0.31.0",
    "tyro>=0.8.4" 
]

[project.urls]
"Homepage" = "https://github.com/grounded-ai"
"Bug Tracker" = "https://github.com/grounded-ai/grounded-eval/issues"